package org.omg.CORBA;


/**
* org/omg/CORBA/FrontendOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA.idl
* Saturday, November 28, 2020 8:36:11 o'clock PM EST
*/

public interface FrontendOperations 
{
  void softwareFailure (String userID);
  void replicaCrash (String userID);
  String createRecord (String userID, String projectID);
  String getRecordCounts (String userID);
  void shutdown ();
} // interface FrontendOperations
