package org.omg.CORBA;


/**
* org/omg/CORBA/FrontendPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA.idl
* Saturday, November 28, 2020 8:36:11 o'clock PM EST
*/

public abstract class FrontendPOA extends org.omg.PortableServer.Servant
 implements org.omg.CORBA.FrontendOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("softwareFailure", new java.lang.Integer (0));
    _methods.put ("replicaCrash", new java.lang.Integer (1));
    _methods.put ("createRecord", new java.lang.Integer (2));
    _methods.put ("getRecordCounts", new java.lang.Integer (3));
    _methods.put ("shutdown", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // org/omg/CORBA/Frontend/softwareFailure
       {
         String userID = in.read_string ();
         this.softwareFailure (userID);
         out = $rh.createReply();
         break;
       }

       case 1:  // org/omg/CORBA/Frontend/replicaCrash
       {
         String userID = in.read_string ();
         this.replicaCrash (userID);
         out = $rh.createReply();
         break;
       }

       case 2:  // org/omg/CORBA/Frontend/createRecord
       {
         String userID = in.read_string ();
         String projectID = in.read_string ();
         String $result = null;
         $result = this.createRecord (userID, projectID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // org/omg/CORBA/Frontend/getRecordCounts
       {
         String userID = in.read_string ();
         String $result = null;
         $result = this.getRecordCounts (userID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // org/omg/CORBA/Frontend/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CORBA/Frontend:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Frontend _this() 
  {
    return FrontendHelper.narrow(
    super._this_object());
  }

  public Frontend _this(org.omg.CORBA.ORB orb) 
  {
    return FrontendHelper.narrow(
    super._this_object(orb));
  }


} // class FrontendPOA
