package org.omg.CORBA;

/**
* org/omg/CORBA/FrontendHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA.idl
* Saturday, November 28, 2020 8:36:11 o'clock PM EST
*/

public final class FrontendHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.CORBA.Frontend value = null;

  public FrontendHolder ()
  {
  }

  public FrontendHolder (org.omg.CORBA.Frontend initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.omg.CORBA.FrontendHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.omg.CORBA.FrontendHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.omg.CORBA.FrontendHelper.type ();
  }

}
