package org.omg.CORBA;


/**
* org/omg/CORBA/Frontend.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA.idl
* Tuesday, December 1, 2020 9:48:02 o'clock PM EST
*/

public interface Frontend extends FrontendOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Frontend
