package org.omg.CORBA;


/**
* org/omg/CORBA/IFrontend.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA.idl
* Wednesday, December 2, 2020 1:27:25 o'clock AM EST
*/

public interface IFrontend extends IFrontendOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IFrontend
