package org.omg.CORBA;

/**
* org/omg/CORBA/IFrontendHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA.idl
* Wednesday, December 2, 2020 1:27:25 o'clock AM EST
*/

public final class IFrontendHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.CORBA.IFrontend value = null;

  public IFrontendHolder ()
  {
  }

  public IFrontendHolder (org.omg.CORBA.IFrontend initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.omg.CORBA.IFrontendHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.omg.CORBA.IFrontendHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.omg.CORBA.IFrontendHelper.type ();
  }

}
