package org.omg.CORBA;


/**
* org/omg/CORBA/IFrontendOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA.idl
* Wednesday, December 2, 2020 1:27:25 o'clock AM EST
*/

public interface IFrontendOperations 
{
  void softwareFailure (String userID);
  void replicaCrash (String userID);
  String createAddItem (String userID, String itemID, String itemName, int quantity, double price);
  String createRemoveItem (String userID, String itemID, int quantity);
  String createListItems (String userID);
  String createPurchaseItems (String userID, String itemID, String dateOfReturn);
  String createReturnItems (String userID, String itemID, String dateOfReturn);
  String createExchangeItem (String userID, String newItemID, String oldItemID, String dateOfExchange);
  String createFindItem (String userID, String itemName);
  void shutdown ();
} // interface IFrontendOperations
